import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import ReduxProvider from "@/redux/ReduxProvider";
import Header from "@/componets/Header";
import { Slide, ToastContainer } from "react-toastify";
import { SocketContextProvider } from "@/lib/SocketContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#1D232A]`}
      >
        <ReduxProvider>
          <SocketContextProvider>
            <div className="flex flex-col min-h-screen">
              <Header />
              <main className="flex-1 overflow-hidden mt-16">
                {children}
              </main>
            </div>
            <ToastContainer
              position="top-right"
              autoClose={4000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick={false}
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light"
              transition={Slide}
            />
          </SocketContextProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
